### ISSUE TITLE
Mercs and items menu overlap on Android?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestSolAndroid#4] opened 2019-12-06 02:35 UTC
Noted while testing on an emulator

![image](https://user-images.githubusercontent.com/1063833/70290087-d4c55900-17a4-11ea-98bf-3e78d0321dbd.png)

**Comment by BenjaminAmos** [comment] 2019-12-06 10:59
The UI issue should have been fixed in https://github.com/MovingBlocks/DestinationSol/commit/b147789d79897556084fe98bb89d66f41a93ddad . When I ran the latest code in both repositories, the issue did not show for me. Are you running an older Destination Sol branch? It might help to un-install the app from the emulator before re-installing it, so that the app cache is cleared.
![AndroidUIScreenShot](https://user-images.githubusercontent.com/24301287/70317970-c9ab1100-1816-11ea-8e75-8627a5de92a8.png)

**Comment by NicholasBatesNZ** [comment] 2019-12-13 02:49
Can't reproduce on latest.

**Closed as completed** 2019-12-13 21:09 UTC
Labels: bug, help wanted
